<a href="https://colab.research.google.com/github/cauancalmeida/Data_Science_studies/blob/main/Pandas_IO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

##Lendo via CSV

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/pandas/refs/heads/main/superstore_data.csv')

In [3]:
df.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [4]:
df_2 = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/pandas/refs/heads/main/superstore_data_ponto_virgula.csv', sep=';')

In [5]:
df_2.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [8]:
dados_sus = pd.read_csv('/content/dados_sus.csv',sep=';',encoding='ISO-8859-1', skiprows=3, skipfooter=9, engine='python')

In [9]:
dados_sus

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"
5,Amapá,"1120973,34","1268740,33","974651,24","1141137,32","866346,18","1440978,95","1426659,48","1475551,38","1651341,43",...,"3253399,45","2946398,44","2416019,23","2203732,04","2218532,26","2566919,60","2802886,34","2817849,31","3188210,98","309860092,59"
6,Tocantins,"3441592,69","4985688,85","6205612,60","4984482,09","5511002,46","4927934,22","5445602,28","5413710,38","5596669,50",...,"9155572,36","8390267,72","8729632,49","7770885,66","527840,46","675277,05","419553,49","319160,87","1357751,33","1020028272,64"
7,Maranhão,"10723506,39","13559679,41","13985142,36","14809416,46","14505727,38","14908091,32","15784899,40","15195312,89","14951277,75",...,"35473489,49","32219037,29","30077152,72","33200778,47","31942670,33","30783403,58","30738750,31","30924484,99","39663677,48","3871069498,04"
8,Piauí,"7985142,43","10079928,25","10298372,45","10775976,33","10398360,88","10528253,88","11040107,92","10549176,40","10899198,97",...,"19908573,27","25663537,49","20230782,72","22389215,72","18911604,50","20883972,79","22689390,32","19400269,01","20018325,75","2280888802,74"
9,Ceará,"15539821,90","25735101,55","28724625,75","30676457,06","30604453,47","31272395,18","30925391,36","27851438,72","30362719,90",...,"56019506,33","61719491,69","56625919,77","59074596,33","56916499,66","50849353,22","52078218,88","53171253,41","62079618,54","6591836650,18"
10,Rio Grande do Norte,"5947814,08","9509755,83","10352238,59","10855108,50","11160168,19","10475071,38","11386349,96","10640817,47","11336030,28",...,"26337808,77","27579658,62","27721340,38","26048003,33","24737052,09","23846816,35","28044464,51","26317613,74","23306498,68","2660122027,15"
11,Paraíba,"10723002,45","11386274,47","12053643,87","12653528,76","12215107,11","12256928,49","12755413,77","12872578,37","12558296,11",...,"27294311,05","23288213,79","19480481,07","19988426,94","18418075,59","18099514,43","19524543,63","21302722,77","25750897,89","2614919044,63"
12,Pernambuco,"14393949,89","24181400,95","29991302,71","34806197,97","32147987,35","32239094,89","32685640,76","35457038,66","33668261,46",...,"74914677,43","77232881,01","71715677,42","66555628,25","78904176,21","70978052,15","83846222,44","75562664,69","83870992,73","8581189975,91"
13,Alagoas,"6243726,32","8376622,16","8408336,22","9090794,82","9338771,45","10068210,08","9887061,61","9373432,00","9563580,50",...,"18453860,49","19995280,39","18185986,17","18871513,02","18597375,56","17805273,37","17543184,88","18526929,38","22118639,05","2236415402,51"
14,Sergipe,"2780750,11","3676483,16","5051473,61","5046063,36","4741151,56","5401259,63","5521904,44","5238398,50","5187912,19",...,"10313262,56","11404646,48","10741986,60","12278300,58","12264609,05","11454427,82","12060864,70","13003816,54","13321494,41","1215853015,00"
15,Bahia,"21211522,47","28189304,95","34181483,52","39026934,13","42949566,82","47025972,04","47481695,17","46931248,28","44883379,31",...,"84204991,86","83478081,57","80540324,01","81250834,02","86257814,00","85871122,17","79961693,17","81992571,15","98746333,07","9791541570,52"
16,Minas Gerais,"45671659,76","70194037,10","79231336,95","77136537,58","80554440,63","94758522,83","85360064,11","84722528,10","84601757,95",...,"165759955,94","171048093,95","175439696,53","178279152,74","175253226,91","172509435,62","174722161,98","177270694,34","200471045,07","20418737536,66"
17,Espírito Santo,"5456723,98","9102212,86","10249595,97","11253833,56","10198619,17","13364258,29","13035374,08","12588595,77","12727433,30",...,"33474963,98","32364742,01","38569356,14","35748380,19","32030401,25","33674687,78","39642483,39","40243896,20","45490499,45","3405850698,58"
18,Rio de Janeiro,"23025258,52","28394310,93","44567062,94","44054604,82","44911021,15","48056212,24","49872379,35","50912706,60","49270352,76",...,"99331352,01","96339615,99","88305239,94","86995649,35","86776500,97","90416725,95","94179674,42","85583557,95","106837295,81","10337391164,52"
19,São Paulo,"91678473,48","148677526,82","156087269,23","161227125,43","187119397,64","187291126,07","194398399,48","184854516,35","188636359,55",...,"367648996,72","349900969,68","354117254,42","345733068,79","335084865,66","330489045,98","355149525,60","348827130,99","392946147,42","41396604304,13"
20,Paraná,"38266347,46","55384670,52","53801318,85","52460306,69","54419620,71","57811688,48","58094241,83","56982774,90","57549082,26",...,"109720663,59","129529222,48","122702263,26","129647873,97","126859051,02","120037066,76","122122779,12","132622112,72","140264608,52","14681514706,67"
21,Santa Catarina,"16504913,45","25651429,11","26743524,89","27181488,26","26845308,18","29909762,04","30789135,84","31250854,33","30019676,93",...,"61267297,89","65467585,93","71781494,82","69414431,71","68460616,55","70333079,37","71970474,56","74337524,03","81376630,57","7835011163,40"
22,Rio Grande do Sul,"30931325,46","57363420,01","51547794,07","56673338,49","48397733,07","52413429,62","56636376,98","56113054,70","55356224,30",...,"100579287,65","102609965,59","104401019,54","117458292,46","108853890,98","111760506,80","119992419,94","111797400,70","130155185,16","12764391179,92"
23,Mato Grosso do Sul,"5377392,11","7002472,61","8423933,19","8797487,68","9770421,80","10905392,18","10249299,82","9671553,45","10218511,05",...,"18858844,44","19877080,68","19247894,51","19497210,85","22023126,25","19629591,55","21693311,15","24337295,63","25168195,34","2324525096,33"
24,Mato Grosso,"4795299,01","8684882,23","7886243,14","8794109,79","9231645,40","10221763,77","9163314,28","9243148,81","9052354,89",...,"16834650,98","19704915,36","20746227,60","22727405,20","20506039,58","19583803,46","19120141,68","18349376,92","19611032,61","2180119781,15"
25,Goiás,"15310637,29","22258668,68","21442515,75","20921212,45","21615970,67","18270043,87","20540517,13","20650730,67","20868443,56",...,"40606222,82","46229357,10","44889588,33","45529496,23","43037600,45","44147353,21","46127763,88","42742773,93","45592686,49","4973573613,47"
26,Distrito Federal,"4745919,19","7632480,67","9647203,26","11098732,99","12891719,72","12850125,67","12565646,74","13710857,89","13165106,20",...,"25269773,34","26526196,39","20056592,11","20856249,30","20459325,27","22991567,76","23527050,29","22766952,62","31831917,45","2592422853,56"
27,Total,"408424859,23","613174269,21","664043058,38","686662861,42","715803639,49","752181563,64","764990284,76","750608648,28","752962642,15",...,"1484010417,62","1514160823,72","1477904466,14","1489983146,21","1464196395,75","1441199605,05","1513991196,49","1500612299,36","1687562138,38","172481760138,88"

##Lendo via Planilhas

In [10]:
url = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'

In [11]:
dados_co2 = pd.read_excel(url)

In [12]:
dados_co2.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
pd.ExcelFile(url).sheet_names

['emissoes_C02', 'emissoes_percapita', 'fontes']

In [14]:
percapita = pd.read_excel(url, sheet_name='emissoes_percapita')

In [15]:
percapita.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
fontes = pd.read_excel(url, sheet_name='fontes')

In [17]:
fontes.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]

In [18]:
intervalo = pd.read_excel(url, sheet_name='emissoes_C02', usecols= 'A:D')

In [19]:
intervalo

              País ISO 3166-1 alpha-3   Ano         Total
0      Afeganistão                AFG  1750  0.000000e+00
1      Afeganistão                AFG  1751  0.000000e+00
2      Afeganistão                AFG  1752  0.000000e+00
3      Afeganistão                AFG  1753  0.000000e+00
4      Afeganistão                AFG  1754  0.000000e+00
...            ...                ...   ...           ...
63099       Global                WLD  2017  3.609674e+10
63100       Global                WLD  2018  3.682651e+10
63101       Global                WLD  2019  3.708256e+10
63102       Global                WLD  2020  3.526409e+10
63103       Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

In [20]:
intervalo_2 = pd.read_excel(url, sheet_name='emissoes_C02', usecols= 'A:D', nrows=10)

In [21]:
intervalo_2

          País ISO 3166-1 alpha-3   Ano  Total
0  Afeganistão                AFG  1750      0
1  Afeganistão                AFG  1751      0
2  Afeganistão                AFG  1752      0
3  Afeganistão                AFG  1753      0
4  Afeganistão                AFG  1754      0
5  Afeganistão                AFG  1755      0
6  Afeganistão                AFG  1756      0
7  Afeganistão                AFG  1757      0
8  Afeganistão                AFG  1758      0
9  Afeganistão                AFG  1759      0

In [22]:
percapita.to_csv('percapita.csv', index=False)

###Google Planilhas

In [23]:
sheet_id='13Q8Rj_HR0w6LgUgIGjEp5-y6UM_-hYZg2YIo1LetDA8'

In [24]:
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [25]:
df_co2 = pd.read_csv(url)

In [26]:
df_co2.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

####outras sheets

In [27]:
sheet_id='13Q8Rj_HR0w6LgUgIGjEp5-y6UM_-hYZg2YIo1LetDA8'
sheet_name = 'emissoes_percapita'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [28]:
df_co2_emissoes = pd.read_csv(url)
df_co2_emissoes.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Óleo,Gás,Cimento,Queima,Outro
0,Afeganistão,AFG,1750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
sheet_name = 'fontes'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'
df_co2_fontes = pd.read_csv(url)
df_co2_fontes.head()

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]

####Desafio

In [36]:
id = '1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw'
url = f'https://docs.google.com/spreadsheets/d/{id}/gviz/tq?tqx=out:csv&sheet'
dado_co2 = pd.read_csv(url)
dado_co2.head()

,Country,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),191.745.115,167.681.579,95.957.742,8.472.111,75.545.827,68.467.956,...,29.650.624,259.295.334,18.562.366,146.235.617,172.896.741,149.789.334,131.694.556,1.632.953,159.824.372,159.824.372
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),553.661.955,544.538.649,543.557.223,70.898.423,836.804.405,912.141.485,...,985.522.312,950.695.879,1.036.293.852,1.099.779.111,113.504.405,1.031.811.348,81.330.073,777.674.934,792.137.069,792.137.069
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819.541.634,124.281.022,683.699.826,638.307.036,645.355.189,605.436.253,...,166.942.319,150.324.046,1.533.630.039,1.668.337.371,160.377.515,1.557.664.358,1.788.786.074,1.782.738.948,169.224.832,169.224.832
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521.831.658,723.537.924,69.630.787,6.724.177.518,6.541.578.914,6.733.479.486,...,5.850.886.105,5.944.654.173,5.942.800.412,5.807.127.723,6.026.181.822,6.080.600.282,6.104.133.912,6.362.975.399,6.481.217.432,6.481.217.432

In [37]:
dados_co2.to_csv('dados_co2.csv', index=False)

##Lendo JSON

In [38]:
import requests
import json

In [59]:
dados_frutas = requests.get('https://fruityvice.com/api/fruit/all')

In [60]:
resultado = json.loads(dados_frutas.text)

In [64]:
resultado

[{'name': 'Persimmon',
  'id': 52,
  'family': 'Ebenaceae',
  'order': 'Rosales',
  'genus': 'Diospyros',
  'nutritions': {'calories': 81,
   'fat': 0.0,
   'sugar': 18.0,
   'carbohydrates': 18.0,
   'protein': 0.0}},
 {'name': 'Strawberry',
  'id': 3,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Fragaria',
  'nutritions': {'calories': 29,
   'fat': 0.4,
   'sugar': 5.4,
   'carbohydrates': 5.5,
   'protein': 0.8}},
 {'name': 'Banana',
  'id': 1,
  'family': 'Musaceae',
  'order': 'Zingiberales',
  'genus': 'Musa',
  'nutritions': {'calories': 96,
   'fat': 0.2,
   'sugar': 17.2,
   'carbohydrates': 22.0,
   'protein': 1.0}},
 {'name': 'Tomato',
  'id': 5,
  'family': 'Solanaceae',
  'order': 'Solanales',
  'genus': 'Solanum',
  'nutritions': {'calories': 74,
   'fat': 0.2,
   'sugar': 2.6,
   'carbohydrates': 3.9,
   'protein': 0.9}},
 {'name': 'Pear',
  'id': 4,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Pyrus',
  'nutritions': {'calories': 57,
   'fat': 0.1,
   'sugar': 10.0,
   'carbohydrates': 15.0,
   'protein': 0.4}},
 {'name': 'Durian',
  'id': 60,
  'family': 'Malvaceae',
  'order': 'Malvales',
  'genus': 'Durio',
  'nutritions': {'calories': 147,
   'fat': 5.3,
   'sugar': 6.75,
   'carbohydrates': 27.1,
   'protein': 1.5}},
 {'name': 'Blackberry',
  'id': 64,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Rubus',
  'nutritions': {'calories': 40,
   'fat': 0.4,
   'sugar': 4.5,
   'carbohydrates': 9.0,
   'protein': 1.3}},
 {'name': 'Lingonberry',
  'id': 65,
  'family': 'Ericaceae',
  'order': 'Ericales',
  'genus': 'Vaccinium',
  'nutritions': {'calories': 50,
   'fat': 0.34,
   'sugar': 5.74,
   'carbohydrates': 11.3,
   'protein': 0.75}},
 {'name': 'Kiwi',
  'id': 66,
  'family': 'Actinidiaceae',
  'order': 'Struthioniformes',
  'genus': 'Apteryx',
  'nutritions': {'calories': 61,
   'fat': 0.5,
   'sugar': 9.0,
   'carbohydrates': 15.0,
   'protein': 1.1}},
 {'name': 'Lychee',
  'id': 67,
  'family': 'Sapindaceae',
  'order': 'Sapindales',
  'genus': 'Litchi',
  'nutritions': {'calories': 66,
   'fat': 0.44,
   'sugar': 15.0,
   'carbohydrates': 17.0,
   'protein': 0.8}},
 {'name': 'Pineapple',
  'id': 10,
  'family': 'Bromeliaceae',
  'order': 'Poales',
  'genus': 'Ananas',
  'nutritions': {'calories': 50,
   'fat': 0.12,
   'sugar': 9.85,
   'carbohydrates': 13.12,
   'protein': 0.54}},
 {'name': 'Fig',
  'id': 68,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Ficus',
  'nutritions': {'calories': 74,
   'fat': 0.3,
   'sugar': 16.0,
   'carbohydrates': 19.0,
   'protein': 0.8}},
 {'name': 'Gooseberry',
  'id': 69,
  'family': 'Grossulariaceae',
  'order': 'Saxifragales',
  'genus': 'Ribes',
  'nutritions': {'calories': 44,
   'fat': 0.6,
   'sugar': 0.0,
   'carbohydrates': 10.0,
   'protein': 0.9}},
 {'name': 'Passionfruit',
  'id': 70,
  'family': 'Passifloraceae',
  'order': 'Malpighiales',
  'genus': 'Passiflora',
  'nutritions': {'calories': 97,
   'fat': 0.7,
   'sugar': 11.2,
   'carbohydrates': 22.4,
   'protein': 2.2}},
 {'name': 'Plum',
  'id': 71,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 46,
   'fat': 0.28,
   'sugar': 9.92,
   'carbohydrates': 11.4,
   'protein': 0.7}},
 {'name': 'Orange',
  'id': 2,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 43,
   'fat': 0.2,
   'sugar': 8.2,
   'carbohydrates': 8.3,
   'protein': 1.0}},
 {'name': 'GreenApple',
  'id': 72,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Malus',
  'nutritions': {'calories': 21,
   'fat': 0.1,
   'sugar': 6.4,
   'carbohydrates': 3.1,
   'protein': 0.4}},
 {'name': 'Raspberry',
  'id': 23,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Rubus',
  'nutritions': {'calories': 53,
   'fat': 0.7,
   'sugar': 4.4,
   'carbohydrates': 12.0,
   'protein': 1.2}},
 {'name': 'Watermelon',
  'id': 25,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Citrullus',
  'nutritions': {'calories': 30,
   'fat': 0.2,
   'sugar': 6.0,
   'carbohydrates': 8.0,
   'protein': 0.6}},
 {'name': 'Lemon',
  'id': 26,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 29,
   'fat': 0.3,
   'sugar': 2.5,
   'carbohydrates': 9.0,
   'protein': 1.1}},
 {'name': 'Mango',
  'id': 27,
  'family': 'Anacardiaceae',
  'order': 'Sapindales',
  'genus': 'Mangifera',
  'nutritions': {'calories': 60,
   'fat': 0.38,
   'sugar': 13.7,
   'carbohydrates': 15.0,
   'protein': 0.82}},
 {'name': 'Blueberry',
  'id': 33,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Fragaria',
  'nutritions': {'calories': 29,
   'fat': 0.4,
   'sugar': 5.4,
   'carbohydrates': 5.5,
   'protein': 0.0}},
 {'name': 'Apple',
  'id': 6,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Malus',
  'nutritions': {'calories': 52,
   'fat': 0.4,
   'sugar': 10.3,
   'carbohydrates': 11.4,
   'protein': 0.3}},
 {'name': 'Guava',
  'id': 37,
  'family': 'Myrtaceae',
  'order': 'Myrtales',
  'genus': 'Psidium',
  'nutritions': {'calories': 68,
   'fat': 1.0,
   'sugar': 9.0,
   'carbohydrates': 14.0,
   'protein': 2.6}},
 {'name': 'Apricot',
  'id': 35,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 15,
   'fat': 0.1,
   'sugar': 3.2,
   'carbohydrates': 3.9,
   'protein': 0.5}},
 {'name': 'Melon',
  'id': 41,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitaceae',
  'genus': 'Cucumis',
  'nutritions': {'calories': 34,
   'fat': 0.0,
   'sugar': 8.0,
   'carbohydrates': 8.0,
   'protein': 0.0}},
 {'name': 'Tangerine',
  'id': 77,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 45,
   'fat': 0.4,
   'sugar': 9.1,
   'carbohydrates': 8.3,
   'protein': 0.0}},
 {'name': 'Pitahaya',
  'id': 78,
  'family': 'Cactaceae',
  'order': 'Caryophyllales',
  'genus': 'Cactaceae',
  'nutritions': {'calories': 36,
   'fat': 0.4,
   'sugar': 3.0,
   'carbohydrates': 7.0,
   'protein': 1.0}},
 {'name': 'Lime',
  'id': 44,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 25,
   'fat': 0.1,
   'sugar': 1.7,
   'carbohydrates': 8.4,
   'protein': 0.3}},
 {'name': 'Pomegranate',
  'id': 79,
  'family': 'Lythraceae',
  'order': 'Myrtales',
  'genus': 'Punica',
  'nutritions': {'calories': 83,
   'fat': 1.2,
   'sugar': 13.7,
   'carbohydrates': 18.7,
   'protein': 1.7}},
 {'name': 'Dragonfruit',
  'id': 80,
  'family': 'Cactaceae',
  'order': 'Caryophyllales',
  'genus': 'Selenicereus',
  'nutritions': {'calories': 60,
   'fat': 1.5,
   'sugar': 8.0,
   'carbohydrates': 9.0,
   'protein': 9.0}},
 {'name': 'Grape',
  'id': 81,
  'family': 'Vitaceae',
  'order': 'Vitales',
  'genus': 'Vitis',
  'nutritions': {'calories': 69,
   'fat': 0.16,
   'sugar': 16.0,
   'carbohydrates': 18.1,
   'protein': 0.72}},
 {'name': 'Morus',
  'id': 82,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Morus',
  'nutritions': {'calories': 43,
   'fat': 0.39,
   'sugar': 8.1,
   'carbohydrates': 9.8,
   'protein': 1.44}},
 {'name': 'Feijoa',
  'id': 76,
  'family': 'Myrtaceae',
  'order': 'Myrtoideae',
  'genus': 'Sellowiana',
  'nutritions': {'calories': 44,
   'fat': 0.4,
   'sugar': 3.0,
   'carbohydrates': 8.0,
   'protein': 0.6}},
 {'name': 'Avocado',
  'id': 84,
  'family': 'Lauraceae',
  'order': 'Laurales',
  'genus': 'Persea',
  'nutritions': {'calories': 160,
   'fat': 14.66,
   'sugar': 0.66,
   'carbohydrates': 8.53,
   'protein': 2.0}},
 {'name': 'Kiwifruit',
  'id': 85,
  'family': 'Actinidiaceae',
  'order': 'Ericales',
  'genus': 'Actinidia',
  'nutritions': {'calories': 61,
   'fat': 0.5,
   'sugar': 8.9,
   'carbohydrates': 14.6,
   'protein': 1.14}},
 {'name': 'Cranberry',
  'id': 87,
  'family': 'Ericaceae',
  'order': 'Ericales',
  'genus': 'Vaccinium',
  'nutritions': {'calories': 46,
   'fat': 0.1,
   'sugar': 4.0,
   'carbohydrates': 12.2,
   'protein': 0.4}},
 {'name': 'Cherry',
  'id': 9,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 50,
   'fat': 0.3,
   'sugar': 8.0,
   'carbohydrates': 12.0,
   'protein': 1.0}},
 {'name': 'Peach',
  'id': 86,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 39,
   'fat': 0.25,
   'sugar': 8.4,
   'carbohydrates': 9.5,
   'protein': 0.9}},
 {'name': 'Jackfruit',
  'id': 94,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Artocarpus',
  'nutritions': {'calories': 95,
   'fat': 0.0,
   'sugar': 19.1,
   'carbohydrates': 23.2,
   'protein': 1.72}},
 {'name': 'Horned Melon',
  'id': 95,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Cucumis',
  'nutritions': {'calories': 44,
   'fat': 1.26,
   'sugar': 0.5,
   'carbohydrates': 7.56,
   'protein': 1.78}},
 {'name': 'Hazelnut',
  'id': 96,
  'family': 'Betulaceae',
  'order': 'Fagales',
  'genus': 'Corylus',
  'nutritions': {'calories': 628,
   'fat': 61.0,
   'sugar': 4.3,
   'carbohydrates': 17.0,
   'protein': 15.0}},
 {'name': 'Pomelo',
  'id': 98,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 37,
   'fat': 0.0,
   'sugar': 8.5,
   'carbohydrates': 9.67,
   'protein': 0.82}},
 {'name': 'Mangosteen',
  'id': 99,
  'family': 'Clusiaceae',
  'order': 'Malpighiales',
  'genus': 'Garcinia',
  'nutritions': {'calories': 73,
   'fat': 0.58,
   'sugar': 16.11,
   'carbohydrates': 17.91,
   'protein': 0.41}},
 {'name': 'Pumpkin',
  'id': 100,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Cucurbita',
  'nutritions': {'calories': 25,
   'fat': 0.3,
   'sugar': 3.3,
   'carbohydrates': 4.6,
   'protein': 1.1}},
 {'name': 'Japanese Persimmon',
  'id': 101,
  'family': ' Ebenaceae',
  'order': ' Ericales',
  'genus': 'Diospyros',
  'nutritions': {'calories': 70,
   'fat': 0.2,
   'sugar': 13.0,
   'carbohydrates': 19.0,
   'protein': 0.6}},
 {'name': 'Papaya',
  'id': 42,
  'family': 'Caricaceae',
  'order': 'Brassicales',
  'genus': 'Carica',
  'nutritions': {'calories': 39,
   'fat': 0.3,
   'sugar': 4.4,
   'carbohydrates': 5.8,
   'protein': 0.5}},
 {'name': 'Annona',
  'id': 103,
  'family': 'Annonaceae',
  'order': 'Rosales',
  'genus': 'Annonas',
  'nutritions': {'calories': 92,
   'fat': 0.29,
   'sugar': 3.4,
   'carbohydrates': 19.1,
   'protein': 1.5}},
 {'name': 'Ceylon Gooseberry',
  'id': 104,
  'family': 'Salicaceae',
  'order': 'Malpighiales',
  'genus': 'Dovyalis',
  'nutritions': {'calories': 47,
   'fat': 0.3,
   'sugar': 8.1,
   'carbohydrates': 9.6,
   'protein': 1.2}}]

In [65]:
dados_norm = pd.json_normalize(resultado)

In [66]:
dados_norm

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

##Buscados dados HTML/XML

In [69]:
dados_html = pd.read_html('https://pt.wikipedia.org/wiki/Lista_de_pa%C3%ADses_por_popula%C3%A7%C3%A3o')

In [71]:
paises = dados_html[0]

In [72]:
paises

,Unnamed: 0,Posição,País (ou território dependente),Estimativa da ONU,Crescimento desde a última estimativa,Estimativa Oficial
0,NaN,1,Índia,1 429 921 746,+269.108.746,Estimativa oficial
1,NaN,2,China,1 426 391 281,+87.778.313,Censo oficial
2,NaN,3,Estados Unidos,339 987 103,+31.241.565,Censo oficial
3,NaN,4,Indonésia,277 184 719,+33.168.546,Estimativa oficial
4,NaN,5,Paquistão,240 215 932,+65.636.932,Estimativa oficial
...,...,...,...,...,...,...
245,NaN,–,Ilha de Ascensão (Reino Unido),1 100,NaN,Estimativa oficial[10]
246,NaN,195,Vaticano,825,NaN,Estimativa oficial
247,NaN,–,Ilhas Cocos (Keeling) (Austrália),596,NaN,Estimativa oficial
248,NaN,–,Tristão da Cunha (Reino Unido),264,NaN,Estimativa oficial[11]
249,NaN,–,Ilhas Pitcairn (Reino Unido),67,NaN,Estimativa oficial

##Pegando dados de um BD

In [4]:
sqlalchemy.__version__

'1.4.54'

In [75]:
#downgrade de versão
pip install --upgrade 'sqlalchemy<2.0'

Collecting sqlalchemy<2.0
  Downloading SQLAlchemy-1.4.54-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<2.0) (3.1.1)
Downloading SQLAlchemy-1.4.54-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 7.0 MB/s eta 0:00:00
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.35
    Uninstalling SQLAlchemy-2.0.35:
      Successfully uninstalled SQLAlchemy-2.0.35
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.4.54 which is incompatible.
Successfully installed sqlalchemy-1.4.54

In [1]:
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect

In [3]:
#criando bando de dados
engine = create_engine('sqlite:///:memory:')

In [5]:
#Código omitido

url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

In [6]:
dados = pd.read_csv(url)

In [7]:
dados.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [8]:
dados.to_sql('clientes', engine, index=False)

438463

In [9]:
inspector = inspect(engine) #pegar indormações do BD

In [10]:
print(inspector.get_table_names()) #retorna nome das tabelas

['clientes']

In [11]:
query ='SELECT * FROM clientes WHERE Categoria_de_renda = "Empregado"'

In [12]:
empregados = pd.read_sql(query, engine)

In [13]:
empregados

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226055,6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226056,6839936,34,Ensino médio,Casado,3,Empregado,Construção Civil,5,135000.0,1,Casa/apartamento próprio
226057,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
226058,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [14]:
empregados.to_sql('empregados', con = engine, index=False)

226059

In [15]:
pd.read_sql_table('empregados', con = engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226055,6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
226056,6839936,34,Ensino médio,Casado,3,Empregado,Construção Civil,5,135000.0,1,Casa/apartamento próprio
226057,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
226058,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [16]:
pd.read_sql_table('empregados', con = engine, columns=['ID_Cliente', 'Grau_escolaridade', 'Rendimento_anual'])

        ID_Cliente Grau_escolaridade  Rendimento_anual
0          5008804   Ensino superior          427500.0
1          5008805   Ensino superior          427500.0
2          5008806      Ensino médio          112500.0
3          5008815   Ensino superior          270000.0
4          5112956   Ensino superior          270000.0
...            ...               ...               ...
226054     6837905      Ensino médio          355050.0
226055     6837906      Ensino médio          355050.0
226056     6839936      Ensino médio          135000.0
226057     6840222      Ensino médio          103500.0
226058     6842885      Ensino médio          121500.0

[226059 rows x 3 columns]

###atualizando dados

In [17]:
query ='SELECT * FROM clientes'
pd.read_sql(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [18]:
query='DELETE FROM clientes WHERE ID_Cliente=5008804'
with engine.connect() as conn:
  conn.execute(query)

<ipython-input-18-670b6b704892>:3: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  conn.execute(query)

In [20]:
pd.read_sql_table('clientes',engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
2,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
3,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [21]:
query = 'UPDATE clientes SET Grau_escolaridade = "Ensino superior" WHERE ID_Cliente = 5008808'
with engine.connect() as conn:
  conn.execute(query)

In [22]:
pd.read_sql_table('clientes',engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
2,5008808,52,Ensino superior,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
3,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

###Desafio

In [23]:
n_engine = create_engine('sqlite:///:memory:')

In [24]:
dados_clientes = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv')

In [27]:
dados_clientes.to_sql('clientes_new',n_engine, index=False)

438463

In [28]:
pd.read_sql_table('clientes_new',n_engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [29]:
def roda_query (query):
  #função para rodar todas as queries
  with n_engine.connect() as conn:
    return conn.execute(query)

In [32]:
query_atualiza = 'UPDATE clientes_new SET Rendimento_anual = "300000" WHERE ID_Cliente = "6840104"'
roda_query(query_atualiza)
pd.read_sql_table('clientes_new',n_engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [36]:
query_deleta = 'DELETE FROM clientes_new WHERE ID_Cliente = "5008809"'
roda_query(query_deleta)
pd.read_sql_table('clientes_new',n_engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

In [46]:
query_insere = 'INSERT INTO clientes_new (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, ' \
        'Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, ' \
        'Rendimento_anual, Tem_carro, Moradia) ' \
        'VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", ' \
        '2, 290000, 0, "Casa/apartamento próprio")'
roda_query(query_insere)
pd.read_sql_table('clientes_new',n_engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio
438462,6850985,33,Doutorado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio